# Generated by Django 5.2.5 on 2025-09-01 01:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'split',
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('percentage', 'Percentage')], default='percentage')),
                ('payment_method', models.CharField(choices=[('pix', 'Pix'), ('bank_transfer', 'Bank Transfer')], default='pix')),
                ('recipient_id', models.CharField(max_length=255)),
                ('account_info', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='split_rules.split')),
            ],
            options={
                'db_table': 'rule',
            },
        ),
    ]
