# Generated by Django 5.2.5 on 2025-08-31 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('split_rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'split',
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('percentage', 'Percentage')], default='percentage')),
                ('payment_method', models.CharField(choices=[('pix', 'Pix'), ('bank_transfer', 'Bank Transfer')], default='pix')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending')),
                ('account_info', models.JSONField()),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='split_rules.split')),
            ],
            options={
                'db_table': 'rule',
            },
        ),
        migrations.DeleteModel(
            name='SplitRules',
        ),
    ]
