# Generated by Django 5.2.5 on 2025-08-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split_rules', '0002_split_rules_delete_splitrules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='status',
        ),
    ]
