# Generated by Django 5.2.5 on 2025-08-31 15:16

from time import timezone
from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('split_rules', '0003_remove_rules_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='split',
            name='is_active',
        ),
        migrations.AddField(
            model_name='rules',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='split',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='split',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active'),
        ),
        migrations.AddField(
            model_name='split',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
