# Generated by Django 5.2.5 on 2025-08-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_rules', '0004_remove_split_is_active_rules_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='recipient_id',
            field=models.CharField(default='wefwe', max_length=255),
            preserve_default=False,
        ),
    ]
