services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .docker.env
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cakto
      POSTGRES_USER: cakto
      POSTGRES_PASSWORD: cakto
    ports:
      - "5434:5432"
    restart: always
